language: java
jdk:
  - openjdk8

install: true
script: mvn -B -q verify

sudo: false

before_install:
  - wget ftp://mirror.reverse.net/pub/apache/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip
  - unzip -qq apache-maven-3.6.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.0
  - export PATH=$M2_HOME/bin:$PATH

cache:
  directories:
  - $HOME/.m2
